apiVersion: apps/v1
kind: Deployment
metadata:
  name: archipelago-api
  labels:
    app: archipelago-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archipelago-api
  template:
    metadata:
      name: archipelago-api
      labels:
        app: archipelago-api
    spec:
      containers:
        - name: archipelago-api
          image: ghcr.io/zgamelogic/archipelago-api:master
          imagePullPolicy: Always
          volumeMounts:
            - name: archipelago-output-volume
              mountPath: "/Archipelago/output"
              readOnly: true

      volumes:
        - name: archipelago-output-volume
          hostPath:
            path: /home/Ben/front-end/archipelago/output
            type: Directory
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-secret

      