apiVersion: apps/v1
kind: Deployment
metadata:
  name: archipelago-api
  labels:
    app: archipelago-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archipelago-api
  template:
    metadata:
      name: archipelago-api
      labels:
        app: archipelago-api
    spec:
      containers:
        - name: archipelago-api
          image: ghcr.io/zgamelogic/archipelago-api:master
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - ls
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
      restartPolicy: Always
      imagePullSecrets:
        - name: ghcr-secret

      