apiVersion: v1
kind: Service
metadata:
  name: archipelago-api
spec:
  selector:
    app: archipelago-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100
  type: NodePort
  